# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd3bbbdba85354df77a3f5f31e683290b9ffcde7d090e0fd2d049272c3ce5181568c601eb834d866e2c7e7089fe8b22f3e5ab07b02f6f3dcd5b03465f2f7b265

test:
  secret_key_base: 48b5a080d5d8cda86c3c4b63d399e1c6244e3fa0794989049df90c3b9a05e4b387701c615595b19cfe242aee2a1c0d6cbd2e50461f0971e41942ead6d3512ad6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
